---
experiments:
  metero_use: ['2m_temperature', # = temperature
               'boundary_layer_height',  # MISSING # Comment out for no_BPL experiments.
               # 'k_index', # MISSING
               'relative_humidity+950', # = humidity * 100
               'surface_pressure', # MISSING
               'total_precipitation', # = ~ precipIntensity
               'u_component_of_wind+950', # speed = windSpeed * 3.6 (from m/s to km/h)
               'v_component_of_wind+950' # direc = windBearing
               ]
  # if True, last two features should be (u,v) of wind, otherwise (speed [km/h], direc)
  use_wind_coordinates: True 
  # If True, timestamps are computed from start/end date, otherwise provided as first feature (format e.g.'2016-01-01 02:00:00')
  compute_time: False
  save_npy: True
  dataset_num: 1
#  model: MLP
#  model: LSTM
#  model: GRU
#  model: GC_LSTM
#  model: nodesFC_GRU
  model: PM25_GNN
#  model: PM25_GNN_nosub

train:
  batch_size: 32
  epochs: 50
  exp_repeat: 3
  hist_len: 1
  pred_len: 336
  weight_decay: 0.0005
  early_stop: 10
  lr: 0.0005

device:
  cuda04:
    knowair_fp: ./data/KnowAir_DS2.npy
    results_dir: ./data/results
    torch_device: cuda:4

wandb:
  entity: split-sources
  project: split-pollution-sources

data:
  metero_var:
    [
      '2m_temperature',
      'boundary_layer_height',
      'relative_humidity+950',
      'surface_pressure',
      'total_precipitation',
      'u_component_of_wind+950', 
      'v_component_of_wind+950'
     ]

dataset:
  data_start: [[2016, 1, 1, 8, 0], GMT] # 2016-01-01 08:00:00
  data_end: [[2020, 12, 31, 23, 0], GMT] # 2020-12-31 23:00:00

  1: 
    train_start: [[2016, 1, 1], GMT] # TODO later also try training w/ 2018
    train_end: [[2017, 12, 31], GMT]
    val_start: [[2019, 1, 1], GMT]
    val_end: [[2019, 12, 31], GMT]
    test_start: [[2020, 1, 1], GMT]
    test_end: [[2020, 12, 31], GMT]

  # 1:
  #   train_start: [[2015, 1, 1], GMT]
  #   train_end: [[2016, 12, 31], GMT]
  #   val_start: [[2017, 1, 1], GMT]
  #   val_end: [[2017, 12, 31], GMT]
  #   test_start: [[2018, 1, 1], GMT]
  #   test_end: [[2018, 12, 31], GMT]

  # 2:
  #   train_start: [[2015, 11, 1], GMT]
  #   train_end: [[2016, 2, 28], GMT]
  #   val_start: [[2016, 11, 1], GMT]
  #   val_end: [[2017, 2, 28], GMT]
  #   test_start: [[2017, 11, 1], GMT]
  #   test_end: [[2018, 2, 28], GMT]

  # 3:
  #   train_start: [[2016, 9, 1], GMT]
  #   train_end: [[2016, 11, 30], GMT]
  #   val_start: [[2016, 12, 1], GMT]
  #   val_end: [[2016, 12, 31], GMT]
  #   test_start: [[2017, 1, 1], GMT]
  #   test_end: [[2017, 1, 31], GMT]
